# Generated by Django 4.2.6 on 2023-10-13 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trends', '0002_alter_keyword_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trend',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
    ]
